export enum Configuration {
  HOST = 'HOST',
  PORT = 'PORT',
  MONGO_URI = 'MONGO_URI',
  // JWT_KEY = 'JWT_KEY',
  JWT_EXP_TIME= 'JWT_EXP_TIME',
  WEB_URL = 'WEB_URL',

  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_TLS = 'EMAIL_TLS',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
}
