version: '2'

services:
  chatprojapi:
    build: .
    container_name: chatproj-api
    restart: always
    network_mode: bridge
    ports:
      - 3005:3000
    volumes:
      - ./upload:/usr/src/app/upload
    environment:
      - MONGO_URI=mongodb://localhost/chatProj
      - HOST=http://localhost
      - PORT=8080
      - JWT_KEY=lfjf

      - VIRTUAL_HOST=chatprojapi.com
      - VIRTUAL_PORT=80
      - DATABASE=chatProj
      - SYNCHRONIZE=false
      - NODE_ENV=production
      - CORS_URLS=http://localhost:4200
      - CORS_METHODS=OPTIONS,GET,HEAD,PUT,PATCH,POST,DELETE