# Cambiar la ip del HOST por la correspondiente al servidor donde se esté corriendo el docker container
# Cambiar la IP de la base de datos de mongo por la correspondiente
# Cambiar las credenciales para la base de datos de mongo correspondiente
# El puerto interno del contenedor debe ser igual al externo para evitar fallos por CORS en el Swagger

version: '2.0'

services:
  chat-proj-api:
    build: .
    container_name: chat-proj-api
    restart: always
#    network_mode: bridge
    ports:
      - 3006:3006
    volumes:
      - ./upload:/usr/src/app/upload
    environment:
      - MONGO_URI=mongodb://admin:admin@mongodb/userManager
      - HOST=http://34.69.232.230
      - PORT=3006
      - JWT_KEY=lfjf

      - VIRTUAL_HOST=chat-projapi.com
      - VIRTUAL_PORT=80
      - DATABASE=chatProj
      - SYNCHRONIZE=false
      - NODE_ENV=development
      - CORS_URLS=http://localhost:4200
      - CORS_METHODS=OPTIONS,GET,HEAD,PUT,PATCH,POST,DELETE
    # networks:
    #   -  mongo_db_default
# networks:
#   mongo_db_default:
#     external: false
#     name: mongo_db_default
#   default:
#     external:
#       name: mongo_db_default
